[package]
name = "log_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5"
flate2 = "1.0.22"
error-chain = "0.12.4"
nom = "7.1.1"
chrono = "0.4"
glob = "0.3.0"